# Generated by Django 3.1.2 on 2020-11-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('slug', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=50)),
                ('content', models.TextField()),
                ('short_desc', models.CharField(default='', max_length=219)),
                ('timestamp', models.DateTimeField()),
                ('published', models.BooleanField(default=True)),
            ],
        ),
    ]
